#!/usr/bin/python3
import os
import subprocess
from datetime import datetime
from login import *

os.path.join(os.path.dirname(os.path.realpath(__file__)), "..", "_site")

if not os.path.isdir(".git"):
    subprocess.call(["git", "init"])
    subprocess.call(["git", "remote", "add", "origin", github_repo_origin])

subprocess.call(["git", "add", "-A"])
subprocess.call(["git", "commit", "-m", f"upload {datetime.now().strftime('%d/%m/%Y %H:%M:%S')}"])
subprocess.call(["git", "push", "-f", f"https://{github_token}@{github_repo_origin.replace('https://','')}"])